// ratesData.js
const ratesData = [
  {
    item_description: "Panal Meeting SME SLPA",
    rate_type: "Hourly",
    category: "Course Development Work",
    cost_type: "A",
    rate: 750.0,
  },
  {
    item_description: "Panal Meeting SME Outsider",
    rate_type: "Hourly",
    category: "Course Development Work",
    cost_type: "A",
    rate: 2000.0,
  },
  {
    item_description: "Refreshments",
    rate_type: "Quantity",
    category: "Course Development Work",
    cost_type: "A",
    rate: 80.0,
  },
  {
    item_description: "Documentation",
    rate_type: "Full Payment",
    category: "Course Development Work",
    cost_type: "A",
    rate: 2000.0,
  },
  {
    item_description: "Transport",
    rate_type: "Full Payment",
    category: "Course Development Work",
    cost_type: "A",
    rate: 2000.0,
  },
  {
    item_description: "Incidental Expenses",
    rate_type: "Quantity",
    category: "Course Development Work",
    cost_type: "A",
    rate: 200.0,
  },
  {
    item_description: "Miscellaneous",
    rate_type: "Full Payment",
    category: "Course Development Work",
    cost_type: "A",
    rate: 200.0,
  },

  {
    item_description: "Senior Training Manager(S.T.M)",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 950.0,
  },
  {
    item_description: "Training Manager(T.M)",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 900.0,
  },
  {
    item_description: "Assistant Training Manager(A.T.M)",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 800.0,
  },
  {
    item_description: "Training Officer(T.O)",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 700.0,
  },
  {
    item_description: "Instructor",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 650.0,
  },
  {
    item_description: "Management Assistant",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 650.0,
  },
  {
    item_description: "Labour",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (MPTI)",
    cost_type: "B",
    rate: 500.0,
  },
  {
    item_description: "Category-A",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (SLPA)",
    cost_type: "B",
    rate: 1350.0,
  },
  {
    item_description: "Category-B",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (SLPA)",
    cost_type: "B",
    rate: 1000.0,
  },
  {
    item_description: "Category-C",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (SLPA)",
    cost_type: "B",
    rate: 500.0,
  },

  {
    item_description: "Category-A",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (Outside)",
    cost_type: "B",
    rate: 2100.0,
  },
  {
    item_description: "Category-B",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (Outside)",
    cost_type: "B",
    rate: 1500.0,
  },
  {
    item_description: "Category-C",
    rate_type: "Hourly",
    category: "Course Delivery Human Resources (Outside)",
    cost_type: "B",
    rate: 1000.0,
  },

  {
    item_description: "Coordination",
    rate_type: "Nos Days",
    category: "Course Delivery Human Resources",
    cost_type: "B",
    rate: 1000.0,
  },
  {
    item_description: "Lecturer Payment(Resource Person)",
    rate_type: "Full Payment",
    category: "Course Delivery Human Resources",
    cost_type: "B",
    rate: 1000.0,
  },
  {
    item_description: "Examination",
    rate_type: "Full Payment",
    category: "Course Delivery",
    cost_type: "B",
    rate: 1000.0,
  },

  {
    item_description: "Handouts",
    rate_type: "Quantity",
    category: "Course Delivery (Materials)",
    cost_type: "B",
    rate: 15.0,
  },
  {
    item_description: "H/Sheet",
    rate_type: "Quantity",
    category: "Course Delivery (Materials)",
    cost_type: "B",
    rate: 2.0,
  },
  {
    item_description: "Magi Pen",
    rate_type: "Quantity",
    category: "Course Delivery (Materials)",
    cost_type: "B",
    rate: 150.0,
  },
  {
    item_description: "File Covers",
    rate_type: "Quantity",
    category: "Course Delivery (Materials)",
    cost_type: "B",
    rate: 15.0,
  },
  {
    item_description: "Other Material",
    rate_type: "Full Payment",
    category: "Course Delivery (Materials)",
    cost_type: "B",
    rate: 1000.0,
  },

  {
    item_description: "Multimedia Projector",
    rate_type: "Quantity_Hourly",
    category: "Course Delivery (Teaching Aid)",
    cost_type: "C",
    rate: 500.0,
  },
  {
    item_description: "Overhead Projector",
    rate_type: "Quantity_Hourly",
    category: "Course Delivery (Teaching Aid)",
    cost_type: "C",
    rate: 500.0,
  },
  {
    item_description: "Chart Stand",
    rate_type: "Quantity_Hourly",
    category: "Course Delivery (Teaching Aid)",
    cost_type: "C",
    rate: 100.0,
  },
  {
    item_description: "Flannel Board",
    rate_type: "Quantity_Hourly",
    category: "Course Delivery (Teaching Aid)",
    cost_type: "C",
    rate: 100.0,
  },
  {
    item_description: "Personal Computer",
    rate_type: "Quantity_Hourly",
    category: "Course Delivery (Teaching Aid)",
    cost_type: "C",
    rate: 500.0,
  },
  {
    item_description: "Other Teaching Aid",
    rate_type: "Full Payment",
    category: "Course Delivery (Teaching Aid)",
    cost_type: "C",
    rate: 500.0,
  },

  {
    item_description: "Auditorium",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 30000.0,
  },
  {
    item_description: "Classroom",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Computer Lab",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Electric & Electronic Lab",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Mechatronic Lab",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Welding Workshop",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Electric & Electronic Workshop",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Training Yard",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Ship Simulator",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },
  {
    item_description: "Fire Simulator",
    rate_type: "Hourly",
    category: "Course Delivery (Teaching Env)",
    cost_type: "C",
    rate: 6000.0,
  },

  {
    item_description: "Transport",
    rate_type: "Full Payment",
    category: "Overheads",
    cost_type: "C",
    rate: 100.0,
  },
  {
    item_description: "Tea (Plain)",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 25.0,
  },
  {
    item_description: "Tea (Milk)",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 90.0,
  },
  {
    item_description: "Snacks",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 100.0,
  },
  {
    item_description: "Meals",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 550.0,
  },
  {
    item_description: "Certificates",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 1000.0,
  },
  {
    item_description: "Certificates Holders",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 200.0,
  },
  {
    item_description: "Other Overheads",
    rate_type: "Full Payment",
    category: "Overheads",
    cost_type: "C",
    rate: 100.0,
  },
  {
    item_description: "Incidental Overheads",
    rate_type: "Quantity",
    category: "Overheads",
    cost_type: "C",
    rate: 1000.0,
  },
  {
    item_description: "Administration",
    rate_type: "Full Payment",
    category: "Overheads",
    cost_type: "C",
    rate: 5000.0,
  },
  {
    item_description: "Marketing Cost",
    rate_type: "Full Payment",
    category: "Overheads",
    cost_type: "C",
    rate: 1000.0,
  },
  {
    item_description: "Maintenance Cost",
    rate_type: "Full Payment",
    category: "Overheads",
    cost_type: "C",
    rate: 1000.0,
  },
];

export default ratesData;
